# Mode: just saucr replication

mode:
  cc: saucr # concurrency control
  ab: saucr # atomic broadcast
  batch: false
  retry: 20

# Sites: 1 server, 5 replicas
site:
  server:
    - ["s101:8101", "s102:8102", "s103:8103", "s104:8104", "s105:8105"]
  client: # each line is a partition
    - ["c01"]

process:
  s101: localhost
  s102: localhost
  s103: localhost
  s104: localhost
  s105: localhost
  c01: localhost

host:
  localhost: 127.0.0.1
